// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Mariusz Woźniak (SP6INA)

pub mod adif;
pub mod astronomy;
pub mod awards;
pub mod backup;
pub mod bandplan;
pub mod callbook;
pub mod callsign_correction;
pub mod clubs;
pub mod contest_rules;
pub mod contest_stats;
pub(crate) mod credentials;
pub mod csv_export;
pub mod database;
pub mod events;
pub mod exchange;
pub mod geo;
pub mod http;
pub mod i18n;
pub mod pga;
pub mod prefix;
pub mod propagation;
pub mod propagation_history;
pub mod qsl_print;
pub mod qso;
pub mod satellite;
pub mod scp;
pub mod service_db;
pub mod sota_export;
pub mod station;
pub mod text;
pub mod xml;
